// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

use std::env;
use std::fs;
use std::path::Path;

use anki_proto_gen::descriptors_path;
use anki_proto_gen::get_services;
use prost_reflect::DescriptorPool;

fn main() {
    let descriptors_path = descriptors_path();
    println!("cargo:rerun-if-env-changed=DESCRIPTORS_BIN");
    println!("cargo:rerun-if-changed={}", descriptors_path.display());

    let descriptors = fs::read(&descriptors_path).expect("reading anki_descriptors.bin");
    let pool = DescriptorPool::decode(descriptors.as_slice()).expect("decoding descriptor pool");
    let (_, backend_services) = get_services(&pool);

    let mut table = String::from(
        "// This file is generated by mobile_bridge/build.rs.\n\
         pub(crate) fn generated_backend_method(service: &str, method: &str) -> Option<(u32, u32)> {\n\
         \x20\x20\x20\x20match (service, method) {\n",
    );

    for service in backend_services {
        for method in service.all_methods() {
            push_match_arm(
                &mut table,
                &service.name,
                &method.name,
                service.index,
                method.index,
            );

            if let Some(collection_service_name) = service.name.strip_prefix("Backend") {
                push_match_arm(
                    &mut table,
                    collection_service_name,
                    &method.name,
                    service.index,
                    method.index,
                );
            }
        }
    }

    table.push_str(
        "        _ => None,\n\
         \x20\x20\x20\x20}\n\
         }\n",
    );

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("backend_methods.rs"), table)
        .expect("writing backend_methods.rs");
}

fn push_match_arm(
    table: &mut String,
    service: &str,
    method: &str,
    service_idx: usize,
    method_idx: usize,
) {
    table.push_str(&format!(
        "        ({service:?}, {method:?}) => Some(({service_idx}, {method_idx})),\n",
    ));
}
